import type { Metadata } from 'next';
import { Cairo } from 'next/font/google';
import './globals.css';

const cairoSans = Cairo({
  variable: '--font-cairo-sans',
  subsets: ['arabic', 'latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className="h-full">
      <body
        className={`${cairoSans.className} antialiased min-h-screen flex flex-col justify-center items-center`}
      >
        <div className="w-full flex-1 flex items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
